---
- hosts: 10.0.11.237
  become: yes
  tasks: 
  - name: execute linex comand
    command: hostname -f
    register: myfirsttaskresult 

  - name: i want to see first task 
    debug:
      msg: "{{myfirsttaskresult}}"