--- 
- hosts: 
  become:
  tasks: 
   - include_tasks: myfile.yml

- name: i want to copy files from ansible 
  copy: 
    src: mystatic
    dest: /home/ubuntu/mystaticfile

- name: i want to install webserver 
  apt: 
    name: apache2
    state: present 
    