--- 
- hosts: 10.0.11.237
  become: yes 
  tasks:
  - name: i want to copy files from ansible 
    copy: 
      src: mystatic
      dest: /home/ubuntu/mystaticfile

  - name: i want to install webserver 
    apt: 
      name: apache2
      state: present 

  - naame: copy dynamic file into node  side 
    template:
      src: myindexfile.j2
      dest: /var/www/html/index.html

  - name: download remote files 
    get_url:
      get_url:
      dest: /home/ubuntu/urlfile
      force_basic_auth: yes 

  handlers: 
  - name: restare 
    service: 
      name: apache2
      state: restartd 
