--- 
- hosts: 10.0.11.237
  become: yes 
  tasks: 
  - include_tasks: myfile.yml

  - name: i want to copy files from ansible 
    copy: 
    src: mystatic
    dest: /home/ubuntu/mystaticfile

  - name: i want to install webserver 
    apt: 
      name: apache2
      state: present 

  - naame: copy dynamic file into node  side 
    template:
      src: myindexfile.j2
      dest: /var/www/html/index.html
